@startuml

!include ../relations.uml/assembly.puml!0
!include ../relations.uml/assembly.puml!1
!include ../relations.uml/assembly.puml!2
!include ../relations.uml/filesupport.puml
!include ../relations.uml/snapshot.puml

interface STORE {
    K: Type
    V: Type
    {field} KVs = list (K * V)
    {field} R = store KVs
    init(): configuration -> R
    add(): K -> V -> R -> R
    find(): K -> R -> option V
    find_all(): K -> R -> list V
}

class KeyListStore
STORE <|--- KeyListStore

class FileinformationStore
STORE <|--- FileinformationStore

class FSnapshotStore
STORE <|--- FSnapshotStore

class FBlockListStore
STORE <|--- FBlockListStore

class KeyListStore {
    K = aid_t
    V = keyinformation
}

KeyListStore o-- keyinformation

class FileinformationStore {
    K = fhash
    V = fileinformation
}

FileinformationStore o-- fileinformation

class FSnapshotStore {
    K = timestamp
    V = snapshot
    create_snapshot()
    finish_snapshot()
}

FSnapshotStore o-- "many" snapshot

class FBlockListStore {
    K = fhash
    V = blockinformation
}

FBlockListStore o-- "many" blockinformation

blockinformation::bsnapshot .left. snapshot::sptimestamp
fileinformation::fsnapshot .right. snapshot::sptimestamp

remove assemblyinformation

@enduml