@startuml snapshot

!theme sunlust

class snapshot {
    sptimestamp: PK<int>
    spendtime: int
    sphost: string
    spuser: string
    spfiles: string[]
}

' note right of snapshot::sptimestamp
'     resolution < 1 ms
' end note

@enduml